name: Secrets Demo

on:
  push:
    branches:
      - main

jobs:

  secret-demo:

    runs-on: ubuntu-latest

    steps:

      - name: Print Secret
        run: |
          echo "Secret Loaded Successfully"

      - name: Use Secret
        run: |
          echo "My Name is ${{ secrets.MY_NAME }}"
