name: Understanding Steps

on:
  push:
    branches:
      - main

jobs:

  learning-job:

    runs-on: ubuntu-latest

    steps:

      - name: Step 1
        run: echo "I am Step 1"

      - name: Step 2
        run: echo "I am Step 2"

      - name: Step 3
        run: |
          pwd
          whoami
          uname -a
