name: Checkout Demo

on:
  push:
    branches:
      - main

jobs:

  checkout-demo:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Show Repository Content
        run: |
          echo "Repository Files:"
          find .
